### ISSUE TITLE
[feature] POST: 유저 동네 업데이트( 추가 및 설정 ) 

### ISSUE THREAD

**Issue by min9120** [woowa-techcamp-2022/web-fleamarket-01#80]
## :briefcase: TASK 개요
사용자 동네 추가 
기본 동네 설정이 가능한 API 
## :white_check_mark: TODO 및 진행현황

- [x] town repo, controller, 

## :alarm_clock: 예상 소요 시간
1h

**Comment by jintak0401** [comment]
투en???
